### ISSUE TITLE
Merge PySDM-examples back into PySDM

### ISSUE THREAD

**Issue by abulenok** [open-atmos/PySDM#1036]
Same for PySDM-examples project

**Comment by slayoo** [comment]
- [ ] phase out `test-time-requirements.txt` and instead use `[project.optional-dependencies]` in a `pyproject.toml` file
- [ ] list all examples in README
- [ ] build and upload the -examples package in CI scripts
- [ ] run example-executing jobs in CI

**Comment by slayoo** [comment]
all what was reasonably needed to be done is done here, closing
