### ISSUE TITLE
remaining TODOs in Srivastava 1982 example

### ISSUE THREAD

**Issue by slayoo** [open-atmos/PySDM#1045]
- [ ] remove `compute_drop_volume_total_volume_ratio` from `example.py`
- [ ] remove `get_pysdm_secondary_products` from `example.py`
- [ ] beef up docstrings (e.g., """interprets parameters from Srivastava 1982 in PySDM context""" in settings.py does not convey the actual logic)
- [ ] rerun notebooks to match current PySDM and example code
- [ ] GPU
- [ ] mention rivastava 1982 package in README?
- [ ] unit tests for same effect of changing dt or c
- [ ] unit test: frag_mass must be smaller than drop size

**Comment by abulenok** [comment]
related to https://github.com/open-atmos/PySDM-examples/pull/210
