### ISSUE TITLE
Identifying terminal velocity seg fault cause

### ISSUE THREAD

**Issue by bradybhalla** [open-atmos/PySDM#1097]
After switching to the Geometric collision kernel in the Shima example, the error trace shows that the seg fault originates from [this line](https://github.com/open-atmos/PySDM/blob/a9b926e8da59c8cfe5020f2c07ae64cd9c94c27e/PySDM/backends/impl_numba/methods/terminal_velocity_methods.py#L60C17-L60C55) in the interpolation implementation.

The problem seems to be that `r_id` is too large because the droplet is larger than any existing datapoint, which causes `b[r_id]` and `c[r_id]` to throw an index out of bounds error in pull request #1095.

Possible fixes could be setting `r_id` to its maximum possible value when the droplet is too large or extrapolating from the data to approximate the terminal velocity.

@edejong-caltech @abulenok

**Comment by slayoo** [comment]
@abulenok @bradybhalla 
What about setting v_term to NaN in that case?

**Comment by bradybhalla** [comment]
That sounds like a good idea.  And also maybe display a warning so it is clear what is happening?

**Comment by slayoo** [comment]
@bradybhalla, after discussing with @abulenok, we realised that NaNs are not a perfect solution as (i) it is hard to track their source in a simulation and (ii) we default to fastmath=True for Numba which makes NaN propagation an undefined behaviour. In #1168, there is an exception introduced in the terminal velocity calculation which asserts if the drop sizes are within supported range.
