### ISSUE TITLE
Create an introductory example in docs

### ISSUE THREAD

**Issue by abulenok** [open-atmos/PySDM#1152]
The example of creating a simulation that will walk through the basic concepts of PySDM

cc @AgnieszkaMakulska

**Comment by slayoo** [comment]
IIUC, if we shift from `pdoc3` to `pdoc` we will also gain support for mermaid diagrams within docstrings which might be helpful: https://pdoc.dev/docs/pdoc.html#render-mermaid-diagrams

**Comment by abulenok** [comment]
related #1164
