### ISSUE TITLE
regression (and a need for adding smoke tests!): ARG example plots do not resemble paper ones anymore

### ISSUE THREAD

**Issue by slayoo** [open-atmos/PySDM#1217]
CC: @claresinger @trontrytel 

Example:
`main` branch: https://github.com/slayoo/PySDM-examples/blob/main/PySDM_examples/Abdul_Razzak_Ghan_2000/figs1-5.ipynb
![image](https://github.com/open-atmos/PySDM/assets/89685/513dc91b-8aa5-41c9-ab86-7cf86523cb8f)

Earlier version of the plot:
![image](https://github.com/open-atmos/PySDM/assets/89685/69621f8e-34f4-4096-8e79-b6fe15a8f30d)

**Comment by claresinger** [comment]
this commit is broken: 9c36aef377e105ae64b5abb6e4cfc3b1e2fb3072 (#1063)
this one is still okay: 94e0477ad48f51420528267010c6766c185fe615 (#1205)

so maybe it's the constants definitions which were added? https://github.com/open-atmos/PySDM/blob/72a789278679aed84ee1d09fc55ba2f1495b38cf/examples/PySDM_examples/Abdul_Razzak_Ghan_2000/aerosol.py#L8-L12

**Comment by slayoo** [comment]
Indeed, just tried v2.33 on Colab and it gives the original result

**Comment by slayoo** [comment]
Here's a potential problem - in the dry-aerosol initialisation logic, the default value of `Mv` is used, which is not the same as the one used within the ARG example, hence we are mixing two different values in one simulation: 
https://github.com/open-atmos/PySDM/blob/72a789278679aed84ee1d09fc55ba2f1495b38cf/PySDM/initialisation/aerosol_composition/dry_aerosol.py#L19

**Comment by slayoo** [comment]
follow up here: #1219 (which will need a new test to ensure that this is related and fixes the problem)

**Comment by claresinger** [comment]
> Here's a potential problem - in the dry-aerosol initialisation logic, the default value of `Mv` is used, which is not the same as the one used within the ARG example, hence we are mixing two different values in one simulation:
> 
> https://github.com/open-atmos/PySDM/blob/72a789278679aed84ee1d09fc55ba2f1495b38cf/PySDM/initialisation/aerosol_composition/dry_aerosol.py#L19

Unfortunately I don't think this is _the_ problem....

**Comment by claresinger** [comment]
But I'm not sure where else in these changes could have impacted the ARG results. https://github.com/open-atmos/PySDM/compare/v2.33...v2.34 And I just double-checked again that 2.33 gives the original result and 2.34 looks different so the change definitely occurred here.

**Comment by slayoo** [comment]
For the record, problem is addressed in #1226 (incl. new test - thank you @claresinger!)

**Comment by slayoo** [comment]
done!
thank you, Clare!
