### ISSUE TITLE
Time-dependent super-droplet sampling and modification

### ISSUE THREAD

**Issue by jtbuch** [open-atmos/PySDM#1331]
Hi @slayoo,

I have been running experiments with PySDM to simulate the injection of a new 'seed' aerosol distribution with distinct properties than the background aerosol distribution used to initialize the simulation. As you might anticipate, this functionality has several applications under the cloud seeding research umbrella, including marine cloud brightening, in-situ growth of ice crystals, and precipitation enhancement. For the rest of the discussion in this issue, I will only focus on the precipitation enhancement case with two modifications of the default PySDM code:

1. [Adding new super-droplets](https://github.com/jtbuch/PySDM/tree/aerosol_injection/examples/PySDM_examples/Buch_et_al_2024): In my first attempt, I tried simulating the injection of seeded aerosols at arbitrary time intervals by adding new super-droplets (SDs). This involved writing a new `inject_particles` (see [here](https://github.com/jtbuch/PySDM/blob/aerosol_injection/examples/PySDM_examples/Buch_et_al_2024/case_files/simulation_time.py#L295C61-L295C77) and [here](https://github.com/jtbuch/PySDM/blob/aerosol_injection/examples/PySDM_examples/Buch_et_al_2024/utils/kinematic_1d_bimodal_time.py#L127)) method in the simulation file, making minor tweaks in relevant methods of the [Displacement](https://github.com/jtbuch/PySDM/blob/aerosol_injection/PySDM/dynamics/displacement.py#L144) and [Collision](https://github.com/jtbuch/PySDM/blob/aerosol_injection/PySDM/dynamics/collisions/collision.py#L182) classes, while also writing a couple of [small](https://github.com/jtbuch/PySDM/blob/aerosol_injection/PySDM/particulator.py#L70) [setter methods](https://github.com/jtbuch/PySDM/blob/aerosol_injection/PySDM/impl/particle_attributes.py#L86) to keep track of the new SDs to avoid array shape mismatches. 
The relevant notebook for running the experiment in a SH2012 environment is available [here](https://github.com/jtbuch/PySDM/blob/aerosol_injection/examples/PySDM_examples/Buch_et_al_2024/plot_script_time.ipynb), where I try to show that despite all the modifications, both displacement and collision-coalescence fail, i.e. there is no change in multiplicity and positions of the seeded SDs, even though the code executes successfully.

2. [Modifying existing super-droplets through the 'hijack and redistribute' method](https://github.com/jtbuch/PySDM/tree/sd_update/examples/PySDM_examples/Buch_et_al_2024): After several stimulating conversations with @claresinger, I implemented her suggested [approximation](https://github.com/jtbuch/PySDM/blob/sd_update/examples/PySDM_examples/Buch_et_al_2024/case_files/simulation_sd_update.py#L267C9-L267C27) of aerosol seeding: a) 'hijack' a cloud SD of a size similar to the desired seed and update the value of all relevant extensive attributes: multiplicity, kappa, water mass etc., b) 'redistribute' the original cloud SD's attributes to its neighboring SDs in a grid cell. This way, I can 'inject' a new seed SD with the appropriate multiplicity attribute to represent the  integrated aerosol concentration. 
As the spectra, coalescence rate, and rain water mixing plots in the associated [notebook](https://github.com/jtbuch/PySDM/blob/sd_update/examples/PySDM_examples/Buch_et_al_2024/plot_script_sd_update.ipynb) indicate, there is a distinct seeding signature for well-chosen values of seed radius and concentration. 

I'd be curious about your thoughts on this approach overall! Specifically, if there is a way to get the code working while adding new SDs, or if there is another way to model seeding in PySDM. One suggestion that both @claresinger and @edejong-caltech made (also something that @kdlamb and I discussed independently) was to introduce a new attribute vector for the SDs that acts like a flag to decide whether a particular SD participates in each step of the simulation. In such a setup, certain seed SDs will behave as 'ghosts' for a while before they are activated at the desired time step and then behave normally.

**Comment by slayoo** [comment]
Thanks @jtbuch & @claresinger!

> One suggestion that both @claresinger and @edejong-caltech made (also something that @kdlamb and I discussed independently) was to introduce a new attribute vector for the SDs that acts like a flag to decide whether a particular SD participates in each step of the simulation

In collisions and out-of-domain precipitation, we flag particles that should no longer take part in the simulation by setting multiplicity to zero or setting the index to n_sd:
https://github.com/open-atmos/PySDM/blob/main/PySDM/backends/impl_numba/methods/collisions_methods.py#L1117-L1128

This ensures that these are properly treated later on in condensation and coalescence summations. Perhaps there is no need for a new attribute?

**Comment by slayoo** [comment]
@jtbuch, @claresinger, apologies that it took longer than expected, but here's a first try at a new `Seeding` dynamic for PySDM based on the above idea of using zero multiplicities as flags for implementing a buffer of super droplets to be used for seeding: https://github.com/open-atmos/PySDM/pull/1367

There is a draft of a simple parcel-model test case currently included in `test_seeding.py`: https://github.com/slayoo/PySDM/blob/sd_injection/tests/unit_tests/dynamics/test_seeding.py

It includes condensation, coalescence and seeding. The seeding logic parameters are not yet robust to temporal resolution - there is just prescribed rate per timestep.

The output plot looks like this (blue lines correspond to background aerosol, red lines to the injected particles):
![image](https://github.com/user-attachments/assets/1b0c7c8a-f09b-480d-a2b5-cd6b512e674f)

Feedback welcome!
In particular, it would be great to identify a simple test case from literature that we could refer to.

**Comment by slayoo** [comment]
(I've refactored a bit the PR today moving the plot-generating example into a Jupyeter notebook - hope this will facilitate trying it out: https://github.com/slayoo/PySDM/blob/sd_injection/examples/PySDM_examples/seeding/hello_world.ipynb)

**Comment by claresinger** [comment]
Hi @slayoo! Thank you - this looks like an awesome first step. I see that you have implemented a time window for the seeding, but not yet a variable for the injection rate, is that correct? And is it also correct that in this example the seeded particle attributes are fixed? 

I think ideally we can have a specified injection rate and also inject particles from some specified distribution, but where the injected particles get randomly sampled from that distribution at each timestep. Maybe this means injecting multiple super particles, with different properties (dry sizes, kappas) and multiplicities at each timestep? 

Possibly it will also interesting to be able to have more than one injection window: e.g. to be able to inject particles for 10 min every 1 hour... this could match up nicely with the variable updraft velocity from the Shipway&Hill examples. But I think if we can implement a variable injection rate then that can almost override the injection time window, by specifying the rate to be zero for some times and nonzero for other times.

@jtbuch How do these extensions sound to you? Are there other features you'd been thinking about for the experiments you want to run?

**Comment by slayoo** [comment]
@claresinger, thanks for following up. Yes, of course, the single time window, injection rate, single-super-droplet-per-step operation and lack of attribute sampling are all temporarily set here to the simplest possible settings. I was just aiming at clarifying how to technically address the idea.

**Comment by claresinger** [comment]
Yes, great! Just adding my two cents on what will be the interesting/physically relevant extensions to work on next. And hopefully my comments on the #1367 are helpful, too.

**Comment by jtbuch** [comment]
Hi @slayoo, I finally got around to running the example and reading the code in more detail. Your implementation of a buffer of super-droplets is quite elegant and much more robust than the strategy I have coded up. 

Besides the comments raised above, I was wondering what the seeding would look like in space for 1D and 2D prescribed flow cases. That is, would the buffer super-droplets be subject to displacement like the rest? Or will the user be able to specify the position of buffer super-droplets once they "activate" them? I plan to look into this once I'm back from my summer break.

In terms of a test case from literature, the best reference I could think of is [Prabhakaran et al. (2023)](https://journals.ametsoc.org/view/journals/atsc/80/6/JAS-D-22-0207.1.xml). However, they use a LES and not a parcel model. @claresinger, I recall us discussing this paper and I wonder if you have a better reference in mind?

**Comment by slayoo** [comment]
Perhaps we could try with this paper as a source of an "example": https://doi.org/10.1175/1520-0450(1997)036%3C1449:CPTHSW%3E2.0.CO;2
![image](https://github.com/user-attachments/assets/0daa964f-7418-477e-bb40-64a2b1ce637c)

**Comment by slayoo** [comment]
Probably this one could also be reproduced: https://doi.org/10.1098/rsta.2012.0086

![image](https://github.com/user-attachments/assets/f799e0e3-c0d7-46d5-909c-9d3b9936a364)

**Comment by claresinger** [comment]
Both of these papers look like good examples to start with because the Parcel environment will be easier than a 1D case to start. 

The LES is more complex than any of the environments we have in PySDM right now, but it will definitely an interesting paper to compare your results to in the future @jtbuch .

**Comment by claresinger** [comment]
Concrete next steps are outlined in issue #1387

**Comment by slayoo** [comment]
let's then close here
