### ISSUE TITLE
reverse flexparser workaround

### ISSUE THREAD

**Issue by AgnieszkaZaba** [open-atmos/PySDM#1421]
Should we reverse our workaround (PR #1412) to frozen dataclass issue in flexparser, since it is resolved?
https://github.com/hgrecco/flexparser/issues/12

**Comment by slayoo** [comment]
indeed, here are two PRs addressing it:
- https://github.com/open-atmos/PySDM/pull/1422
- https://github.com/open-atmos/PyMPDATA/pull/478

Thanks!

**Comment by AgnieszkaZaba** [comment]
Thanks @slayoo!
