### ISSUE TITLE
AŻ: Bolin Table 1 as a new example

### ISSUE THREAD

**Issue by AgnieszkaZaba** [open-atmos/PySDM#1432]

**Comment by AgnieszkaZaba** [comment]
PR #1431

**Comment by slayoo** [comment]
thanks! let's close here then and post comments to the PR

**Comment by AgnieszkaZaba** [comment]
@slayoo Is it intended to move closed issue from PySDM to PyMPDATA-MPI & numba-mpi in [open-atmos-krk-weekly-meeting](https://github.com/orgs/open-atmos/projects/5)?

**Comment by slayoo** [comment]
> @slayoo Is it intended to move closed issue from PySDM to PyMPDATA-MPI & numba-mpi in [open-atmos-krk-weekly-meeting](https://github.com/orgs/open-atmos/projects/5)?

Please elaborate

**Comment by AgnieszkaZaba** [comment]
I'm talking about action done by bot **github-project-automation** (for our open-atoms-krk project board). Above my previous comment I see information about that. I think it is automatic when issue is marked as closed. 

My question is: is it expected to automatically move  (within project board columns) closed issues from "PySDM" column to "PyMPDATA-MPI & numba-mpi" column?
This is exactly what happened.

**Comment by slayoo** [comment]
Weird... of course it's not intended and makes no sense. Thanks for noticing! We need to disable it somehow

**Comment by AgnieszkaZaba** [comment]
https://github.com/orgs/open-atmos/projects/5/workflows/28623959

**Comment by AgnieszkaZaba** [comment]
Actually, now I set them off. And if want to use any of them, we can just set a proper value.

**Comment by slayoo** [comment]
Thanks!
