### ISSUE TITLE
bump devops tests

### ISSUE THREAD

**Issue by AgnieszkaZaba** [open-atmos/PySDM#1449]

**Comment by AgnieszkaZaba** [comment]
I think I didn't commit version change. Right now [previous version](https://github.com/open-atmos/devops_tests/tree/231c989f109a1da47ad77f240db7a6b693983377) of devops-test is used in PySDM.

**Comment by slayoo** [comment]
Indeed, despite the title, we have actually not bumped the `devops_tests` version in https://github.com/open-atmos/PySDM/pull/1403 Thanks for reporting!

However, #1450 seem to contain previously squash-merged commits. 

Here's a new PR which does the bump only: https://github.com/open-atmos/PySDM/pull/1453

**Comment by AgnieszkaZaba** [comment]
@slayoo Thank you!
