### ISSUE TITLE
adapting coagulation examples to the matplotlib v3.10.0

### ISSUE THREAD

**Issue by AgnieszkaZaba** [open-atmos/PySDM#1469]
coagulation:

```
FAILED tests/examples_tests/test_run_examples.py::test_run_examples[/home/runner/work/PySDM/PySDM/examples/PySDM_examples/Berry_1967/example.py] - UserWarning: Ignoring specified arguments in this call because figure with num: 1 already exists
FAILED tests/examples_tests/test_run_examples.py::test_run_examples[/home/runner/work/PySDM/PySDM/examples/PySDM_examples/Berry_1967/example_fig_6.py] - UserWarning: Ignoring specified arguments in this call because figure with num: 1 already exists
```

**Comment by slayoo** [comment]
That is a new feature of matplotlib introduced here: https://github.com/matplotlib/matplotlib/commit/f3359a3b3f696c334bd3631fbce0bf893d6ecbf4
and included in v3.10.0 release

**Comment by AgnieszkaZaba** [comment]
Removing `num=1` fix one issue. The question is: why it was there? I tested plots in both notebooks which are using those plotters and they seem to be fine.

**Comment by slayoo** [comment]
this was addressed in https://github.com/open-atmos/PySDM/pull/1476
