### ISSUE TITLE
make smoke tests based on Pyrcel example not XFAIL (peak suersaturation still does not match)

### ISSUE THREAD

**Issue by slayoo** [open-atmos/PySDM#776]

**Comment by claresinger** [comment]
These probably will also currently fail like https://github.com/atmos-cloud-sim-uj/PySDM/pull/767
But I can add a smoke test to match the temperature and supersaturation from the figure in the docs. 

If we wanted to be fancy we could ask PySDM to call Pyrcel directly and compare the output...

**Comment by slayoo** [comment]
calling Pyrcel is tricky due to the dependencies (but not unfeasible)

for now, renaming this issue and adding its issue as a TODO label in the new smoke test (thank you Clare!!!)

**Comment by claresinger** [comment]
This is fixed now with the smaller tolerances / Scipy solver, right?

**Comment by slayoo** [comment]
this one need to remain open for the TODO label in the code not to raise CI failure, and the TODO label is there to remind us of revisiting the PySDM solver behaviour at some point

**Comment by slayoo** [comment]
reopening as there is still one TODO in the code marked with this issue id:
https://github.com/atmos-cloud-sim-uj/PySDM/blob/20301d7a214cbe71b2588f2b51a1602655a45498/tests/smoke_tests/pyrcel/test_parcel_example.py#L64

**Comment by claresinger** [comment]
Closing in favor of #1246 which more accurately describes this issue with updated information.
