### ISSUE TITLE
check all constants from Lowe et al example against ICPM code

### ISSUE THREAD

**Issue by claresinger** [open-atmos/PySDM#899]
check molar masses and densities of all compounds in aerosol definitions with Liine

**Comment by slayoo** [comment]
@claresinger shall we close it given the current match between the example and the paper?

**Comment by slayoo** [comment]
@claresinger shall we close it given the current match between the example and the paper?

**Comment by slayoo** [comment]
@claresinger PySDM-examples CI started to fail as there as still TODOs marked with this issue id there:

PySDM_examples/Lowe_et_al_2019/aerosol_code.py (TODO #899: SOA1 or SOA2 unclear from the paper)

**Comment by claresinger** [comment]
Let's relabel that TODO with #604 and close this issue?
