### ISSUE TITLE
Add Products for Condensation and Evaporation Rates on Activated Droplets

### ISSUE THREAD

**Issue by jb-mackay** [open-atmos/PySDM#930]
Add a product for total mass addition or loss rate due to condensation/evaporation.

@edejong-caltech

**Comment by slayoo** [comment]
To better understand, please provide a use case (incl. environment type).
Is the idea to be able to extract the part of water that condensed vs. that evaporated within a single timestep assuming some droplets grow and some droplets evaporate? (which is indeed not discernible from just the moments of the spectrum).

**Comment by jb-mackay** [comment]
Yes, exactly - the idea is to be able to decompose the total mass change in a single timestep into condensation and evaporation components so that we can see where these processes occur in the cloud, their strengths, and how other dynamics impact them.
