### ISSUE TITLE
Implementation Revisions for Breakup Paper

### ISSUE THREAD

**Issue by edejong-caltech** [open-atmos/PySDM#997]
- [x] Add mass-weighted sampling from FSD for empirical options (Straub, etc.) (re: Axel Seifert's comment)
- [ ] Implement additional breakup parameterizations needed for comparison to McFarquhar 2004, Srivastava [x], Straub [x], Low & List (in progress)
- [ ] Use tanh consistently as approximation of erfinv
- [x] Check out inconsistent return statement in breakup kernel -- merge PR?
- [ ] Avoid bracket indexing within breakup

Related to PySDM-examples:
- [x] Comparison to analytic Srivastava @abulenok 
- [ ] Convergence study with number of superdroplets to this analytic case @abulenok 
- [ ] Comparison to Straub box model results -- steady state size distribution, possibly include Low & List
- [ ] Re-run single column cases after updates to kernels
- [ ] Extended domain/high updraft version of the 1D KiD case
- [ ] Investigate PSDs in the high precip grid-boxes for the 1D case

**Comment by slayoo** [comment]
also worth double-checking this list: https://github.com/atmos-cloud-sim-uj/PySDM/issues?q=is%3Aissue+is%3Aopen+label%3Abreakup

**Comment by abulenok** [comment]
Is this issue still relevant?

**Comment by edejong-caltech** [comment]
No, I will close the issue :)
